<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>PNDQuestTeleop</AssemblyName>
    <RootNamespace>PNDQuestTeleop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.10.0" />
    <PackageReference Include="StereoKit" Version="0.3.11" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
  </ItemGroup>
</Project>
