ADAM_PHYSICAL_JOINTS_31 = [
    "dof_pos/hipPitch_Left",
    "dof_pos/hipRoll_Left",
    "dof_pos/hipYaw_Left",
    "dof_pos/kneePitch_Left",
    "dof_pos/anklePitch_Left",
    "dof_pos/ankleRoll_Left",
    "dof_pos/hipPitch_Right",
    "dof_pos/hipRoll_Right",
    "dof_pos/hipYaw_Right",
    "dof_pos/kneePitch_Right",
    "dof_pos/anklePitch_Right",
    "dof_pos/ankleRoll_Right",
    "dof_pos/waistRoll",
    "dof_pos/waistPitch",
    "dof_pos/waistYaw",
    "dof_pos/neckYaw",
    "dof_pos/neckPitch",
    "dof_pos/shoulderPitch_Left",
    "dof_pos/shoulderRoll_Left",
    "dof_pos/shoulderYaw_Left",
    "dof_pos/elbow_Left",
    "dof_pos/wristYaw_Left",
    "dof_pos/wristPitch_Left",
    "dof_pos/wristRoll_Left",
    "dof_pos/shoulderPitch_Right",
    "dof_pos/shoulderRoll_Right",
    "dof_pos/shoulderYaw_Right",
    "dof_pos/elbow_Right",
    "dof_pos/wristYaw_Right",
    "dof_pos/wristPitch_Right",
    "dof_pos/wristRoll_Right",
]

ADAM_COMMAND_JOINTS_19 = [
    "dof_pos/waistRoll",
    "dof_pos/waistPitch",
    "dof_pos/waistYaw",
    "dof_pos/neckYaw",
    "dof_pos/neckPitch",
    "dof_pos/shoulderPitch_Left",
    "dof_pos/shoulderRoll_Left",
    "dof_pos/shoulderYaw_Left",
    "dof_pos/elbow_Left",
    "dof_pos/wristYaw_Left",
    "dof_pos/wristPitch_Left",
    "dof_pos/wristRoll_Left",
    "dof_pos/shoulderPitch_Right",
    "dof_pos/shoulderRoll_Right",
    "dof_pos/shoulderYaw_Right",
    "dof_pos/elbow_Right",
    "dof_pos/wristYaw_Right",
    "dof_pos/wristPitch_Right",
    "dof_pos/wristRoll_Right",
]

LEFT_SHARPA_JOINT_NAMES = [
    "left_thumb_CMC_FE",
    "left_thumb_CMC_AA",
    "left_thumb_MCP_FE",
    "left_thumb_MCP_AA",
    "left_thumb_IP",
    "left_index_MCP_FE",
    "left_index_MCP_AA",
    "left_index_PIP",
    "left_index_DIP",
    "left_middle_MCP_FE",
    "left_middle_MCP_AA",
    "left_middle_PIP",
    "left_middle_DIP",
    "left_ring_MCP_FE",
    "left_ring_MCP_AA",
    "left_ring_PIP",
    "left_ring_DIP",
    "left_pinky_CMC",
    "left_pinky_MCP_FE",
    "left_pinky_MCP_AA",
    "left_pinky_PIP",
    "left_pinky_DIP",
]
RIGHT_SHARPA_JOINT_NAMES = [
    name.replace("left_", "right_", 1) for name in LEFT_SHARPA_JOINT_NAMES
]
SHARPA_JOINT_NAMES = LEFT_SHARPA_JOINT_NAMES + RIGHT_SHARPA_JOINT_NAMES
