uint64 timestamp_ns

bool has_left_wrist_joint
uint32 left_wrist_joint_dimension
float32[] left_wrist_joint

bool has_left_wrist_eef
uint32 left_wrist_eef_dimension
float32[] left_wrist_eef
string left_wrist_eef_frame

bool has_right_wrist_joint
uint32 right_wrist_joint_dimension
float32[] right_wrist_joint

bool has_right_wrist_eef
uint32 right_wrist_eef_dimension
float32[] right_wrist_eef
string right_wrist_eef_frame

uint32 hand_joint_dimension
bool has_left_hand_joint
float32[] left_hand_joint
bool has_right_hand_joint
float32[] right_hand_joint

bool valid
